microservice:
  replicaCount: 1

  image:
    repository: asia-south1-docker.pkg.dev/project-75c9b927-531d-4e58-a2b/auth-api/auth-api
    tag: "latest"
    pullPolicy: Always

  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 8081

  env:
    - name: AUTH_API_PORT
      value: "8081"
    - name: USERS_API_ADDRESS
      value: "http://users-api:8083"
    - name: ZIPKIN_URL
      value: "http://zipkin:9411/api/v2/spans"

  envFromSecret:
    - name: JWT_SECRET
      secretName: jwt-secret
      secretKey: jwt-secret

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  hpa:
    enabled: false

  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false
