apiVersion: v2
name: frontend
description: Frontend service
version: 1.0.0

dependencies:
  - name: microservice
    version: "1.0.0"
    repository: "oci://asia-south1-docker.pkg.dev/project-75c9b927-531d-4e58-a2b/helm"
